

###
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "name": "qwerty",
    "password": "qwertyu",
    "password2": "qwertyu",
    "email": "qwertyu"
}

###
POST http://localhost:4000/users/login 
Content-Type: application/json

{
    "name": "234567",
    "password": "234567"
}
###
GET http://localhost:3000/getGameData
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjM0NTY3IiwiaWF0IjoxNzM3MzI2NjcwLCJleHAiOjE3MzczMjcyNzB9.5Fyp59cMzmG0-sJszmjJPWkYeFo4jUWVEwkTVIqcuV

###
GET http://localhost:3000/userinformation
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjM0NTY3IiwiaWF0IjoxNzM3MzI0Njk2LCJleHAiOjE3MzczMjUyOTZ9.CDZjpL47XrdOh4BdmZLmTmz1bm6WEotPXv7eEmii_l8